INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Carlos Pérez', TO_DATE('2015-03-01', 'YYYY-MM-DD'), 'carlos.perez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Ana Gómez', TO_DATE('2018-05-15', 'YYYY-MM-DD'), 'ana.gomez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('María González', TO_DATE('2016-10-20', 'YYYY-MM-DD'), 'maria.gonzalez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Juan Martínez', TO_DATE('2019-09-12', 'YYYY-MM-DD'), 'juan.martinez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Laura Sánchez', TO_DATE('2017-08-05', 'YYYY-MM-DD'), 'laura.sanchez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Luis Ramírez', TO_DATE('2014-04-25', 'YYYY-MM-DD'), 'luis.ramirez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Sofía Díaz', TO_DATE('2020-02-18', 'YYYY-MM-DD'), 'sofia.diaz@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Daniel López', TO_DATE('2013-11-30', 'YYYY-MM-DD'), 'daniel.lopez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Elena Pérez', TO_DATE('2018-06-10', 'YYYY-MM-DD'), 'elena.perez@universidad.edu.co');
INSERT INTO Profesor (Nombre, Fecha_contratacion, Correo) VALUES ('Diego Martínez', TO_DATE('2015-12-03', 'YYYY-MM-DD'), 'diego.martinez@universidad.edu.co');

INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('José López', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'jose.lopez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('María Rodríguez', TO_DATE('1998-09-20', 'YYYY-MM-DD'), 'maria.rodriguez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Juan García', TO_DATE('1999-03-12', 'YYYY-MM-DD'), 'juan.garcia@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Laura Martínez', TO_DATE('2001-07-05', 'YYYY-MM-DD'), 'laura.martinez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Carlos Sánchez', TO_DATE('1997-05-18', 'YYYY-MM-DD'), 'carlos.sanchez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Ana López', TO_DATE('2002-11-30', 'YYYY-MM-DD'), 'ana.lopez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Lucía Pérez', TO_DATE('1998-12-15', 'YYYY-MM-DD'), 'lucia.perez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Diego Gómez', TO_DATE('2000-09-28', 'YYYY-MM-DD'), 'diego.gomez@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Sofía Ruiz', TO_DATE('2001-04-03', 'YYYY-MM-DD'), 'sofia.ruiz@correo.com');
INSERT INTO Estudiante (Nombre_estudiante, Fecha_nacimiento, Correo) VALUES ('Elena Díaz', TO_DATE('1999-08-22', 'YYYY-MM-DD'), 'elena.diaz@correo.com');

INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Matemáticas', 3, 1);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Inglés', 2, 2);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Historia', 4, 3);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Biología', 3, 4);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Física', 3, 5);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Química', 3, 6);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Literatura', 2, 7);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Economía', 4, 8);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Arte', 2, 9);
INSERT INTO Curso (Nombre_curso, Creditos, id_profesor) VALUES ('Música', 2, 10);

INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-01-10', 'YYYY-MM-DD'), 1, 1);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-01-15', 'YYYY-MM-DD'), 2, 2);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-02-01', 'YYYY-MM-DD'), 3, 3);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-02-05', 'YYYY-MM-DD'), 4, 4);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-02-20', 'YYYY-MM-DD'), 5, 5);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-03-05', 'YYYY-MM-DD'), 6, 6);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-03-15', 'YYYY-MM-DD'), 7, 7);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-03-20', 'YYYY-MM-DD'), 8, 8);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-04-02', 'YYYY-MM-DD'), 9, 9);
INSERT INTO Matricula (Fecha_matriucla, id_curso, id_estudiante) VALUES (TO_DATE('2023-04-10', 'YYYY-MM-DD'), 10, 10);

INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (100000, TO_DATE('2023-02-10', 'YYYY-MM-DD'), 'Credit', 1);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (150000, TO_DATE('2023-03-05', 'YYYY-MM-DD'), 'Credit', 2);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (200000, TO_DATE('2023-04-15', 'YYYY-MM-DD'), 'Debit', 3);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (250000, TO_DATE('2023-05-20', 'YYYY-MM-DD'), 'Debit', 4);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (300000, TO_DATE('2023-06-10', 'YYYY-MM-DD'), 'Credit', 5);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (350000, TO_DATE('2023-07-15', 'YYYY-MM-DD'), 'Debit', 6);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (400000, TO_DATE('2023-08-20', 'YYYY-MM-DD'), 'Credit', 7);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (450000, TO_DATE('2023-09-25', 'YYYY-MM-DD'), 'Debit', 8);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (500000, TO_DATE('2023-10-30', 'YYYY-MM-DD'), 'Credit', 9);
INSERT INTO Pagos (monto, fecha_pago, tipo_pago, Id_estudiante) VALUES (550000, TO_DATE('2023-11-05', 'YYYY-MM-DD'), 'Debit', 10);
